nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_headers: ['*']
        max_age: 3600
        allow_credentials: true
        origin_regex: true
    paths:
        '^/': ~