services:
  backend:
    build:
      context: ./home_cycl_home_api
    ports:
      - "3333:3333"
    volumes:
      - ./home_cycl_home_api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=home_cycl_home
    command: npm run dev

  frontend:
    build:
      context: ./home_cycl_home_front
    ports:
      - "3000:3000"
    volumes:
      - ./home_cycl_home_front:/app
      - /app/node_modules
    command: npm start

  db:
    image: postgres:14
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: home_cycl_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
