version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5544:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  http:
    build:
      context: ./home_cycl_home_api_sf
      dockerfile: nginx/Dockerfile
    volumes:
      - ./home_cycl_home_api_sf:/app
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./home_cycl_home_api_sf
    volumes:
      - ./home_cycl_home_api_sf:/app
      - symfony_vendor:/app/vendor
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  frontend:
    build:
      context: ./home_cycl_home_front
    ports:
      - "3000:3000"
    volumes:
      - ./home_cycl_home_front:/home_cycl_home_front
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - NODE_ENV=development
    networks:
      - app-network

volumes:
  pgdata:
  symfony_vendor:

networks:
  app-network:
