services:
  symfony:
    build:
      context: ./home_cycl_home_api_sf
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./home_cycl_home_api_sf:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - app-network

  frontend:
    build:
      context: ./home_cycl_home_front
    ports:
      - "4000:3000"
    volumes:
      - ./home_cycl_home_front:/app
      - /app/node_modules
    command: npm start
    networks:
      - app-network
