services:
  db:
    image: postgis/postgis:14-3.3
    ports:
      - "5544:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
      context: ./home_cycl_home_api_sf
      dockerfile: nginx/Dockerfile
    volumes:
      - public_data:/app/public
    depends_on:
      - backend
    ports:
      - "82:80"
    networks:
      - app-network

  backend:
    build:
      context: ./home_cycl_home_api_sf
    volumes:
      - ./home_cycl_home_api_sf:/app
      - symfony_vendor:/app/vendor
      - public_data:/app/public
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network
    extra_hosts:       
      - "host.docker.internal:host-gateway"
      
volumes:
  pgdata:
  symfony_vendor:
  public_data:

networks:
  app-network:
