name: Lint and Prettier Check

on:
  push:
    branches: [dev]

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint (block on warnings)
        run: npm run lint -- --max-warnings=0

      - name: Run prettier check
        run: npm run prettier:check
