name: CI/CD Pipeline

on:
  push:

env:
  NODE_VERSION: 18
  PHP_VERSION: 8.4

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Frontend Dependencies
        working-directory: ./home_cycl_home_front
        run: npm install

      - name: Run lint (block on warnings)
        working-directory: ./home_cycl_home_front
        run: npm run lint -- --max-warnings=0

      - name: Run prettier check
        working-directory: ./home_cycl_home_front
        run: npm run prettier:check

  test:
    runs-on: ubuntu-latest
    needs: lint 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, json
          coverage: none

      - name: Install Frontend Dependencies
        working-directory: ./home_cycl_home_front
        run: npm install

      - name: Install Backend Dependencies
        working-directory: ./home_cycl_home_api_sf
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run frontend tests
        working-directory: ./home_cycl_home_front
        run: npm test -- --watchAll=false

      - name: Run backend tests
        working-directory: ./home_cycl_home_api_sf
        run: php bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

    env:
      DB_ENV: ${{ github.ref == 'refs/heads/main' && vars.DB_PROD_ENV || vars.DB_DEV_ENV }}
      BACK_ENV: ${{ github.ref == 'refs/heads/main' && vars.BACK_PROD_ENV || vars.BACK_DEV_ENV }}
      FRONT_ENV: ${{ github.ref == 'refs/heads/main' && vars.FRONT_PROD_ENV || vars.FRONT_DEV_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update project via Git
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            if [ ! -d "/home/${{ secrets.VPS_USER }}/home_cycl_home/.git" ]; then
              rm -rf /home/${{ secrets.VPS_USER }}/home_cycl_home
              git clone git@github.com:${{ github.repository }} /home/${{ secrets.VPS_USER }}/home_cycl_home
            else
              cd /home/${{ secrets.VPS_USER }}/home_cycl_home
              git fetch origin main
              git reset --hard origin/main
            fi
          EOF

      - name: Deploy backend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd /home/${{ secrets.VPS_USER }}/home_cycl_home

            echo "DB_ENV=$DB_ENV" > .env

            cd /home/${{ secrets.VPS_USER }}/home_cycl_home/home_cycl_home_api_sf

            echo "BACK_ENV=$BACK_ENV" > .env

            mkdir -p "../backups"
            BACKUP_NAME="backup_$(date +%Y%m%d_%H%M%S)"
            rsync -a --exclude='.git' ./ "../backups/$BACKUP_NAME"

            docker compose down
            sudo fuser -k 82/tcp
            docker compose up --build -d --remove-orphans

            sleep 10
            docker compose exec backend php bin/console doctrine:migrations:migrate --no-interaction
          EOF

      - name: Deploy frontend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF

            cd /home/${{ secrets.VPS_USER }}/home_cycl_home/home_cycl_home_front

            echo "FRONT_ENV=$FRONT_ENV" > .env
            
            npm install --omit=dev
            npm run build --verbose

            if ! command -v serve &> /dev/null; then
              npm install -g serve
            fi

            if pm2 describe front > /dev/null 2>&1; then
              pm2 restart front
            else
              pm2 start "sh -c 'npx serve -s build -l 4000'" --name front
            fi
          EOF
